# Generated by Django 2.1.15 on 2020-08-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reciple'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciple',
            new_name='Recipe',
        ),
    ]
